spring:
  datasource:
    url: jdbc:mysql://localhost:3306/neptuno
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect